// Generated by https://quicktype.io

export interface General {
  action:       Action;
  notification: Notification;
}

export interface Action {
  type: number;
}

export interface Notification {
  androidNotificationId: number;
  groupedNotifications:  any[];
  notificationId:        string;
  templateName:          string;
  templateId:            string;
  title:                 string;
  body:                  string;
  lockScreenVisibility:  number;
  fromProjectNumber:     string;
  priority:              number;
  additionalData:        AdditionalData;
  rawPayload:            string;
}

export interface AdditionalData {
}
